import ChakraThemeProvider from "@/providers/ChakraThemeProvider";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <ChakraThemeProvider>
          <Header />
          {children}
          <Footer />
        </ChakraThemeProvider>
      </body>
    </html>
  );
}
